name: Vercel Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-vercel:
    name: Deploy to Vercel (triggered after CI)
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          VERCEL_DEPLOY_HOOK_URL="${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          if [ -z "$VERCEL_DEPLOY_HOOK_URL" ]; then
            echo "🔒 VERCEL_DEPLOY_HOOK_URL secret is not set. Skipping deploy."
            exit 1
          fi

          echo "Triggering Vercel deploy via Deploy Hook..."
          PAYLOAD=$(printf '{"gitCommit":"%s","branch":"%s"}' "${{ github.event.workflow_run.head_sha }}" "${{ github.event.workflow_run.head_branch }}")
          curl -s -X POST "$VERCEL_DEPLOY_HOOK_URL" -H "Content-Type: application/json" -d "$PAYLOAD"
          echo "Deploy hook triggered."
